spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alessiofiore/ic-spring-cloud-config.git
          clone-on-start: true
server:
  port: ${PORT:8060}
